### ISSUE TITLE
ReferenceError: ShowMyHomework is not defined

### ISSUE THREAD

**Issue by Vreslia** [edqx/node-smhw#13]
async function name(){
    const client = new ShowMyHomework.Client();
    const school = await client.searchSchools("Elk Valley Elementary");
}

name();

**Comment by edqx** [comment]
Hi,
You need to import the library.

try writing
```ts
const ShowMyHomework = require("node-smhw");
```
at the top of your file.

Hope that helps.

**Comment by Vreslia** [comment]
Still not working
