### ISSUE TITLE
ReferenceError: id is not defined

### ISSUE THREAD

**Issue by Vreslia** [edqx/node-smhw#14]
ReferenceError: id is not defined
    client.login(school[1],id, "ddddd", "ssssss").then(() => {

**Comment by edqx** [comment]
Hi, I'm going to assume, judging by your last issue, that you don't know how to use JavaScript.

You also copied the example I have in my README wrong, it's supposed to be `school[56871].id`, with a period `.` not a comma `,`.

I also don't think you know what `school[56871]` is, and I doubt it will exist, so your code won't work either way. Consider using `school[0]` instead.

**Comment by edqx** [comment]
Please stop posting issues to do with your inability to use the language. I'm not going to give you support for general programming issues, only issues related to the node-smhw library.
