### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Fyse** [edqx/node-smhw#2]
Hi, is the getTodo method shown in the example still active? Whenever I try running it, it returns:
`(node:8069) UnhandledPromiseRejectionWarning: TypeError: client.getTodo is not a function`

**Comment by edqx** [comment]
Nope sorry it's `.getTasks()` now I believe. https://github.com/edqx/node-smhw/blob/d3b4cd300e97636bd081c108f9abe37b71b4e6c2/src/Client.js#L473

**Comment by edqx** [comment]
68400cf0ee209d1b0ddd8ca87bea295efe982ca3

**Comment by Fyse** [comment]
yeah, thought so when I saw getTasks in another example file. thanks!
